name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: clone
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/banira0428/okayama-univ-fes
      - name: set remote
        run: cd okayama-univ-fes && git remote add upstream https://github.com/oucrc-org/okayama-univ-fes
      - name: fetch
        run: cd okayama-univ-fes && git fetch upstream
      - name: checkout
        run: cd okayama-univ-fes && git checkout master
      - name: merge
        run: cd okayama-univ-fes && git merge upstream/master
      - name: push
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: cd okayama-univ-fes && git push https://banira0428:${PERSONAL_ACCESS_TOKEN}@github.com/banira0428/okayama-univ-fes

